### ISSUE TITLE
Sprint N1

### ISSUE THREAD

**Issue by echedey-ls** [ManuelHuesoBejar/Subj_Robotics#5]
No creo que el nombre sea el más apropiado, pero la esencia será la misma: cada uno que tome voluntariamente las tareas concretas, plazo cíclico de 1 semana máximo. Repetimos proceso después de eso.

# Objetivos sobre el control
| Nombre | Archivos | Objetivos | Concreciones | Hecho | Desarrollo por |
|--------|--------|--------|--------|--------|--------|
| Sensor pos. lineal | `linear_sensor.?pp` | Wrapper de un sens. resistivo para obtener desplazamiento lineal | Similar al rotativo que ya hay. En todo caso prestar atención a la conversión grados --> desplz. | No |
| Actuador rotativo | `rotary_actuator.?pp` | Encapsulado actuador rotativo, del stepper y sensor rotativo. Si puede ser, P<ID> también. | Usar ref [1]. | No |
| Actuador lineal | `linear_actuator.?pp` | Clase para encapsular el actuador lineal; protegerlo frente a mal funcionamiento | Es como un actuador rotativo | No |
| Actuador servo | `servo_actuator.?pp` | Otra clase para encapsular actuador mediante servo realimentado | `class Servo_feedback: public Actuator`. Importante no usar nombre más simples para que no se confunda con la librería, usar la `Servo.h` | No |
| Watchdog actuadores | `actuator.?pp` | Crear un método watchdog para ver que no aumenta significativamente el error (frente a fallos por lazo de posición, por si se lleva golpes) | Un filtro o un tope del error permitido. Que sea modificable y leible en ejecución. Llamado desde método move por defecto. Incluir algún atributo para el ajuste. | No |

# Objetivos sobre comandar el robot
| Nombre | Archivos | Objetivos | Concreciones | Hecho | Desarrollo por |
|--------|--------|--------|--------|--------|--------|
| Structura Node | `nodes.hpp` | Crear estructura para encapsular información de posición+rotación | - | Sí | Lucas |
| Structura Pose | `poses.hpp` | Estructura con la información de cada posición articular | - | Por subsanar | Lucas |
| Archivos cinemáticas | `kinematics.?pp` | Implementar las cinemáticas como traducción de Structs Pose y Node | Serían para nuestro modelo en específico. Cada función debe devolver códigos de error, por si la liamos parda (singularidad, fuera del área de trabajo, imposible alcanzar rotación), lo que implica que hay una estructura que no se modifica (tipo `const`) y otra que sí (pues esa ya no es `const`, vaya). Las referencias son muy monas, por cierto. Acelerar los cálculos es objeto de estudio muchas veces. Se puede pasar por el forro del background. | Imposible [primero las dos anteriores porfi] |

# Encapsulado Robot
| Nombre | Archivos | Objetivos | Concreciones | Hecho | Desarrollo por |
|--------|--------|--------|--------|--------|--------|
| Literalmente el Robot | `nombre-modelo.?pp` | Encapsular dentro de una clase todo lo que es específico del robot | Más a largo plazo. Registrar articulaciones modularmente? Calculadoras de cinemáticas? | No | - | 

# Integración / comms con PC
No es tan crítico, es por normalizar la salida y si hacemos un script para ordenador, que pueda leerlo homogéneamente.
| Nombre | Archivos | Objetivos | Concreciones | Hecho | Desarrollo por |
|--------|--------|--------|--------|--------|--------|
| Wrappers Serial | `serial_wrappers.?pp` | Hacer funciones (que pudieran ser tipo friend) para imprimir propiedades de todo: estructuras pose, node; actuadores, tipo, ID y estado; fallos; el estado global... | Prioridad no elevada. Algún método para leer nodes o poses estaría chulo para comandarlo desde el ordenador. | Desarrollo limitado, por el resto de integraciones | - | 

Un par de notas en general:
1. Que todas las clases que manejen o puedan manejar IO tengan un método `.begin()` para ponerlo en el `void setup()` y configurar, al menos, los pines que utilice.
2. Usar herencia / polimorfismo, como sea conveniente. Sensores resistivos heredan de resistive_sensor, y actuadores de Actuator, etc.

Referencias:
[1] [Librería steppers](https://github.com/laurb9/StepperDriver)

# Estoy postponiendo
1. Efector final
2. Interfaz gráfica en el Arduino
    1. Tampoco hemos valorado en otro lado, TBF.
4. Comandos a través de Serial o cualquier otro tipo de entrada.

#### Fecha último edit:
2023-04-24

**Comment by echedey-ls** [comment]
@ManuelHuesoBejar @Lucas-Go-Vel @DiegoRPeinado @chernobilly69
Ya he realizado un tremendo compendio de objetivos que podéis ir adoptando. Cualquier duda, aclaración o halago me decís. Os quiero <3.

**Comment by ManuelHuesoBejar** [comment]
Tiene muy buena pinta @echedey-ls. Qué profesional, trabajando con Sprints, podemos hacerlos semanales calculando bien la carga de trabajo. Este finde voy a terminar la parte CAD, ¿Podríais ir avanzando vosotros el código porfa?

**Comment by echedey-ls** [comment]
@ManuelHuesoBejar Claro, pues.
 Esto no es de participación obligatoria, sobretodo quienes estáis a otras cosas.
Por supuesto esto es un exceso para un sprint, la cosa es discriminar algunas.
Salu2 bb.
